# Hello World example for DTU biosustain and DTU bioengineering Data Club

name: Hello World example # define name of workflow

on:
  push: # trigger workflow on push to main branch
    branches:
      - main

jobs:
  say-hello-world:
    runs-on: ubuntu-latest #Github's docker image with kubernetes
    steps:
    - uses: actions/checkout@v4 # checkout the code from the repo
    - name: update_pip
      run: python3 -m pip install --upgrade pip

    - name: install_cow_say
      run: pip install cowsay
    - name: say-hello-world_cowsay
      run: cowsay -c cheese -t "hey therer"
    - name: install_cowpy
      run: pip install cowpy
    - name: print_cowpy
      run: cowpy -c tux "hi there"
    - name: cowpy_from_bin
      run: python bin/cowpy.py
    
    - name: list
      run: ls -l
    - name: get_directory
      run: pwd
