# Hello World example for DTU biosustain and DTU bioengineering Data Club

name: Hello World example # define name of workflow

on:
  push: # trigger workflow on push to main branch
    branches:
      - main

jobs:
  say-hello-world:
    runs-on: ubuntu-latest #Github's docker image with kubernetes
    steps:
    - name: biosustain
      run: echo "Hello DTU biosustain!"
    - name: bioengineering
      run: echo "Hello DTU bioengineering!"
    - name: install_cow_say
      run: pip install cowsay
    - name: say-hello-world_cowsay
      run: cowsay -c cheese -t "hey therer"
    - name: install_cowpy
      run: pip install cowpy
    - name: print_cowpy
      run: cowpy -c tux 'hi there'
